spring:
  thymeleaf:
    mode: HTML
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
server:
  port: 8888